export const GET_MOVIE = "GET_MOVIE"
export const GET_MOVIE_DETAILS = " GET_MOVIE_DETAILS";
export const GET_MOVIE_VIDEO = " GET_MOVIE_VIDEO";
export const GET_BEST_MOVIES = " GET_BEST_MOVIES";
export const GET_ALL_MOVIES = "  GET_ALL_MOVIES";